linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell

linters-settings:
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - testdata
  # Skip typecheck validation - known issue with indirect dependencies
  # Code builds and tests correctly. GitHub Actions workflow uses golangci-lint-action
  # which handles dependency resolution properly.

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    - linters:
        - typecheck
      text: "undefined:"
