#!/bin/bash
set -euo pipefail

# ============================================================================
# Tokyo-IA AutoDev Agent
# Generates native code for Android, iOS, and Web platforms
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BRIDGE_FILE="$PROJECT_ROOT/simulator/output/platform_bridge.json"
BRAND_FILE="$PROJECT_ROOT/simulator/output/brand_tokens.json"
OUTPUT_BASE="$PROJECT_ROOT/output"

# Read target platform from environment variable (default: all)
TARGET_PLATFORM="${TARGET_PLATFORM:-all}"

echo "🤖 Tokyo-IA AutoDev Agent"
echo "========================="
echo ""
echo "Target Platform: $TARGET_PLATFORM"

# Check if required files exist
if [ ! -f "$BRIDGE_FILE" ]; then
    echo "❌ Error: platform_bridge.json not found"
    exit 1
fi

if [ ! -f "$BRAND_FILE" ]; then
    echo "❌ Error: brand_tokens.json not found"
    exit 1
fi

echo "✓ Found platform bridge and brand tokens"

# Create output directories
mkdir -p "$OUTPUT_BASE/android" "$OUTPUT_BASE/ios" "$OUTPUT_BASE/web"

# Extract brand colors
PRIMARY_COLOR=$(jq -r '.colors.primary' "$BRAND_FILE")
PROJECT_NAME=$(jq -r '.project_name' "$BRAND_FILE")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "  Project: $PROJECT_NAME"
echo "  Primary Color: $PRIMARY_COLOR"

# ============================================================================
# ANDROID CODE GENERATION
# ============================================================================

if [ "$TARGET_PLATFORM" = "all" ] || [ "$TARGET_PLATFORM" = "android" ]; then
    echo ""
    echo "📱 Generating Android code..."
    
    # Generate MainActivity.kt
    cat > "$OUTPUT_BASE/android/MainActivity.kt" << EOF
package com.tokyoia.app

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.coordinatorlayout.widget.CoordinatorLayout
import com.google.android.material.appbar.MaterialToolbar
import android.widget.TextView
import android.view.Gravity

/**
 * Main Activity for $PROJECT_NAME
 * Auto-generated by Tokyo-IA AutoDev Agent
 * Generated at: $TIMESTAMP
 */
class MainActivity : AppCompatActivity() {
    
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        
        // Setup toolbar
        val toolbar = findViewById<MaterialToolbar>(R.id.toolbar)
        setSupportActionBar(toolbar)
        supportActionBar?.title = "$PROJECT_NAME"
        
        // Setup content
        val contentText = findViewById<TextView>(R.id.content_text)
        contentText.text = "Welcome to $PROJECT_NAME"
    }
}
EOF
    
    # Generate activity_main.xml
    cat > "$OUTPUT_BASE/android/activity_main.xml" << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- 
  Activity Main Layout for $PROJECT_NAME
  Auto-generated by Tokyo-IA AutoDev Agent
  Generated at: $TIMESTAMP
-->
<androidx.coordinatorlayout.widget.CoordinatorLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.google.android.material.appbar.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <com.google.android.material.appbar.MaterialToolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="$PRIMARY_COLOR"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    </com.google.android.material.appbar.AppBarLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:padding="16dp"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <TextView
            android:id="@+id/content_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:text="Welcome to $PROJECT_NAME"
            android:textSize="18sp"
            android:textColor="#000000" />

    </FrameLayout>

</androidx.coordinatorlayout.widget.CoordinatorLayout>
EOF
    
    echo "  ✓ MainActivity.kt"
    echo "  ✓ activity_main.xml"
fi

# ============================================================================
# iOS CODE GENERATION
# ============================================================================

if [ "$TARGET_PLATFORM" = "all" ] || [ "$TARGET_PLATFORM" = "ios" ]; then
    echo ""
    echo "🍎 Generating iOS code..."
    
    # Generate MainViewController.swift
    cat > "$OUTPUT_BASE/ios/MainViewController.swift" << EOF
import UIKit

/**
 * Main View Controller for $PROJECT_NAME
 * Auto-generated by Tokyo-IA AutoDev Agent
 * Generated at: $TIMESTAMP
 */
class MainViewController: UIViewController {
    
    // MARK: - UI Components
    
    private let contentLabel: UILabel = {
        let label = UILabel()
        label.text = "Welcome to $PROJECT_NAME"
        label.font = UIFont.systemFont(ofSize: 18, weight: .regular)
        label.textColor = .black
        label.textAlignment = .center
        label.translatesAutoresizingMaskIntoConstraints = false
        return label
    }()
    
    // MARK: - Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        setupConstraints()
    }
    
    // MARK: - Setup
    
    private func setupUI() {
        title = "$PROJECT_NAME"
        view.backgroundColor = .white
        
        // Setup navigation bar
        navigationController?.navigationBar.prefersLargeTitles = false
        navigationController?.navigationBar.barTintColor = UIColor(hexString: "$PRIMARY_COLOR")
        navigationController?.navigationBar.tintColor = .white
        navigationController?.navigationBar.titleTextAttributes = [.foregroundColor: UIColor.white]
        
        // Add subviews
        view.addSubview(contentLabel)
    }
    
    private func setupConstraints() {
        NSLayoutConstraint.activate([
            contentLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            contentLabel.centerYAnchor.constraint(equalTo: view.centerYAnchor)
        ])
    }
}

// MARK: - UIColor Extension

extension UIColor {
    convenience init?(hexString: String) {
        var hex = hexString.trimmingCharacters(in: .whitespacesAndNewlines)
        hex = hex.replacingOccurrences(of: "#", with: "")
        
        var rgb: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&rgb)
        
        let r = CGFloat((rgb & 0xFF0000) >> 16) / 255.0
        let g = CGFloat((rgb & 0x00FF00) >> 8) / 255.0
        let b = CGFloat(rgb & 0x0000FF) / 255.0
        
        self.init(red: r, green: g, blue: b, alpha: 1.0)
    }
}
EOF
    
    echo "  ✓ MainViewController.swift"
fi

# ============================================================================
# WEB CODE GENERATION
# ============================================================================

if [ "$TARGET_PLATFORM" = "all" ] || [ "$TARGET_PLATFORM" = "web" ]; then
    echo ""
    echo "🌐 Generating Web code..."
    
    # Generate App.tsx
    cat > "$OUTPUT_BASE/web/App.tsx" << EOF
import React from 'react';
import './App.css';

/**
 * Main App Component for $PROJECT_NAME
 * Auto-generated by Tokyo-IA AutoDev Agent
 * Generated at: $TIMESTAMP
 */
const App: React.FC = () => {
  return (
    <main className="scaffold">
      <header className="app-bar">
        <h1>$PROJECT_NAME</h1>
      </header>
      <div className="container">
        <div className="content">
          <span className="welcome-text">Welcome to $PROJECT_NAME</span>
        </div>
      </div>
    </main>
  );
};

export default App;
EOF
    
    # Generate App.css
    cat > "$OUTPUT_BASE/web/App.css" << EOF
/**
 * Styles for $PROJECT_NAME
 * Auto-generated by Tokyo-IA AutoDev Agent
 * Generated at: $TIMESTAMP
 */

.scaffold {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  background-color: #ffffff;
}

.app-bar {
  background-color: $PRIMARY_COLOR;
  color: #ffffff;
  padding: 16px 24px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.app-bar h1 {
  margin: 0;
  font-size: 20px;
  font-weight: 500;
}

.container {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px;
}

.content {
  text-align: center;
}

.welcome-text {
  font-size: 18px;
  color: #000000;
}
EOF
    
    echo "  ✓ App.tsx"
    echo "  ✓ App.css"
fi

echo ""
echo "✅ Code generation complete!"
echo ""
echo "📁 Output locations:"
[ "$TARGET_PLATFORM" = "all" ] || [ "$TARGET_PLATFORM" = "android" ] && echo "  Android: $OUTPUT_BASE/android/"
[ "$TARGET_PLATFORM" = "all" ] || [ "$TARGET_PLATFORM" = "ios" ] && echo "  iOS: $OUTPUT_BASE/ios/"
[ "$TARGET_PLATFORM" = "all" ] || [ "$TARGET_PLATFORM" = "web" ] && echo "  Web: $OUTPUT_BASE/web/"

echo ""
echo "✨ AutoDev agent complete!"
